In [1]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('CO2_Emissions_Canada.csv')
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
1794,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.2,11.3,25,260
1026,VOLKSWAGEN,BEETLE TDI (modified),COMPACT,2.0,4,M6,D,8.8,6.1,7.7,37,208
7171,MERCEDES-BENZ,AMG E 53 4MATIC+ Cabriolet,SUBCOMPACT,3.0,6,A9,Z,12.5,9.0,10.9,26,245
5061,LEXUS,RX 350 L AWD,SUV - SMALL,3.5,6,AS8,X,13.1,9.4,11.1,25,268
5171,MERCEDES-BENZ,METRIS PASSENGER,SPECIAL PURPOSE VEHICLE,2.0,4,A7,Z,12.3,10.3,11.4,25,268

In [5]:
cat_cols = ['Make',	'Model', 'Vehicle Class']

for col in cat_cols:
    df[col] = df[col].str.lower()

df = df.drop_duplicates()

x = df.drop(columns=['CO2 Emissions(g/km)'])
y = df['CO2 Emissions(g/km)']
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.2, random_state=42)

In [10]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 16.9 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [11]:
!pip install mlflow dagshub

Collecting mlflow
  Downloading mlflow-3.13.0-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 3.8 MB/s eta 0:00:00
Collecting dagshub
  Downloading dagshub-0.7.0-py3-none-any.whl.metadata (12 kB)
Collecting mlflow-skinny==3.13.0 (from mlflow)
  Downloading mlflow_skinny-3.13.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.8 MB/s eta 0:00:00
Collecting mlflow-tracing==3.13.0 (from mlflow)
  Downloading mlflow_tracing-3.13.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<49,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (48.0.1)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.0.3-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.50)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading databricks_sdk-0.117.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.49.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Collecting boto3 (from dagshub)
  Downloading boto3-1.43.29-py3-none-any.whl.metadata (6.6 kB)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.2.0 (from dagshub)
  Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.1)
Collecting botocore<1.44.0,>=1.43.29 (from boto3->dagshub)
  Downloading botocore-1.43.29-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3->dagshub)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.7)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.3)
Downloading mlflow-3.13.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 99.8 MB/s eta 0:00:00:00:010:01
Downloading mlflow_skinny-3.13.0-py3-none-any.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 101.8 MB/s eta 0:00:00
Downloading mlflow_tracing-3.13.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 71.9 MB/s eta 0:00:00
Downloading dagshub-0.7.0-py3-none-any.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.1/273.1 kB 21.1 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 6.2 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 12.1 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 10.5 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 16.6 MB/s eta 0:00:00
Downloading huey-3.0.3-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 6.3 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 11.5 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading boto3-1.43.29-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 10.0 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading botocore-1.43.29-py3-none-any.whl (15.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 91.6 MB/s eta 0:00:00:00:010:01
Downloading databricks_sdk-0.117.0-py3-none-any.whl (936 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 936.9/936.9 kB 43.9 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 16.0 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.2 MB/s eta 0:00:00
Downloading s3transfer-0.18.0-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.6/88.6 kB 7.2 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 8.2 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, mypy-extensions, marshmallow, jmespath, gunicorn, graphql-core, dacite, backoff, typing-inspect, graphql-relay, gql, docker, botocore, skops, s3transfer, graphene, Flask-CORS, dataclasses-json, databricks-sdk, dagshub-annotation-converter, boto3, mlflow-tracing, mlflow-skinny, dagshub, mlflow
Successfully installed Flask-CORS-6.0.5 appdirs-1.4.4 backoff-2.2.1 boto3-1.43.29 botocore-1.43.29 dacite-1.6.0 dagshub-0.7.0 dagshub-annotation-converter-0.2.0 databricks-sdk-0.117.0 dataclasses-json-0.6.7 docker-7.1.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.0.0 huey-3.0.3 jmespath-1.1.0 marshmallow-3.26.2 mlflow-3.13.0 mlflow-skinny-3.13.0 mlflow-tracing-3.13.0 mypy-extensions-1.1.0 pathvalidate-3.3.1 s3transfer-0.18.0 semver-3.0.4 skops-0.14.0 treelib-1.8.0 typing-inspect-0.9.0

In [12]:
import dagshub
dagshub.init(
    repo_owner='anni0955', 
    repo_name='CO2-Emission', 
    mlflow=True
)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=11e4b49c-881d-4700-934e-c831c1c5defe&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=ad1a5f55a9bb23c620e50533c0bf61eebae1a2df87942ba57b7f3fcdc5b63c5c

Accessing as anni0955

Initialized MLflow to track repo "anni0955/CO2-Emission"

Repository anni0955/CO2-Emission initialized!

In [13]:
import mlflow 
mlflow.set_experiment('EXP 1 - Model Selection')

2026/06/15 02:55:14 INFO mlflow.tracking.fluent: Experiment with name 'EXP 1 - Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/0950dcd8164144569083eb70f558a873', creation_time=1781492114213, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1781492114213, lifecycle_stage='active', name='EXP 1 - Model Selection', tags={}, trace_location=None, workspace='default'>

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

import optuna

In [20]:
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
683,lincoln,mkt awd,suv - standard,3.5,6,AS6,X,14.8,10.4,12.8,22,294
4574,chevrolet,cruze hatchback,mid-size,1.4,4,M6,X,8.6,6.2,7.5,38,175
410,ford,fusion,mid-size,1.6,4,M6,X,9.4,6.4,8.1,35,186
7204,mini,cooper s 5 door,subcompact,2.0,4,AM7,Z,8.9,6.6,7.9,36,184
4967,jeep,compass,suv - small,2.4,4,A6,X,10.6,7.6,9.3,30,218

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import PowerTransformer, StandardScaler

In [28]:
transformer = ColumnTransformer([
    ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'), ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']),
    ('pt', PowerTransformer(), ['Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)']),
    ('scale', StandardScaler(),['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)'])
])

In [29]:
x_train_trans = transformer.fit_transform(x_train)
x_test_trans = transformer.transform(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [32]:
x_train_trans.shape

(4792, 1585)

In [33]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [46]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical('model', ['LR', 'SVR','DT', 'RF', 'GB', 'XGB'])

        if model_name == 'LR':
            model = LinearRegression()

        
        elif model_name == 'SVR':
            kernel_svm = trial.suggest_categorical('kernel_svm', ['linear', 'poly', 'rbf'])

            if kernel_svm == 'linear':
                c_linear = trial.suggest_float('c_linear', 1e-3, 10, log=True)
                model = SVR(C=c_linear, kernel='linear')

            elif kernel_svm == 'poly':
                c_poly = trial.suggest_float('c_poly', 1e-3, 10, log=True)
                degree_poly = trial.suggest_int('degree_poly', 1, 4)
                model = SVR(C=c_poly, degree=degree_poly, kernel='poly')

            else:
                c_rbf = trial.suggest_float('c_rbf', 1e-3, 10, log=True)
                gamma_rbf = trial.suggest_float('gamma_rbf', 1e-3, 10, log=True)
                model = SVR(C=c_rbf, gamma=gamma_rbf, kernel='rbf')

        elif model_name == 'DT':
            criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'absolute_error', 'poisson', 'squared_error'])
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = DecisionTreeRegressor(criterion=criterion, max_depth=max_depth)

        elif model_name == 'RF':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42, n_jobs=-1)
        
        elif model_name == 'GB':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = GradientBoostingRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42)

        else:
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = XGBRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42, n_jobs=-1)    

        
        model.fit(x_train_trans, y_train)
        mlflow.log_params(trial.params)

        test_y_pred = model.predict(x_test_trans)
        train_y_pred = model.predict(x_train_trans)

        test_MAE = mean_absolute_error(y_test, test_y_pred)
        train_MAE = mean_absolute_error(y_train, train_y_pred)

        test_RMSE = root_mean_squared_error(y_test, test_y_pred)
        train_RMSE = root_mean_squared_error(y_train, train_y_pred)

        mlflow.log_metric('train_MAE', train_MAE)
        mlflow.log_metric('test_MAE', test_MAE)

        mlflow.log_metric('train_RMSE', train_RMSE)
        mlflow.log_metric('test_RMSE', test_RMSE)

        return test_RMSE

In [47]:
study = optuna.create_study(direction='minimize', study_name='Model Selection')

with mlflow.start_run(run_name='Best Model') as parent:
    study.optimize(objective, n_trials=50, n_jobs=-1)
    mlflow.log_params(study.best_params)

    mlflow.log_metric('best_score', study.best_value)

[I 2026-06-15 04:27:05,310] A new study created in memory with name: Model Selection

🏃 View run respected-elk-593 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/e767b0c866154062aed93301bc17cdb4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run thoughtful-rat-278 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/1905d03ca83549b2a4416a4d36538b18
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:27:19,811] Trial 1 finished with value: 21.64943119968877 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.002033317154579505}. Best is trial 1 with value: 21.64943119968877.
[I 2026-06-15 04:27:19,903] Trial 0 finished with value: 14.193096059187859 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.1523152032837918}. Best is trial 0 with value: 14.193096059187859.

🏃 View run capable-perch-526 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/e72e39d5fb4b4516af82956f66f95706
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:27:25,582] Trial 2 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run debonair-mule-858 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/599f266434584aa59d17525fa915374b
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:27:35,493] Trial 4 finished with value: 11.150812301602922 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.23730384930821516}. Best is trial 2 with value: 3.899796879593596.

🏃 View run debonair-stoat-801 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d31a88819b0345c5b725eb286651bc35
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:27:52,539] Trial 3 finished with value: 6.697643144151929 and parameters: {'model': 'DT', 'criterion': 'absolute_error', 'max_depth': 15}. Best is trial 2 with value: 3.899796879593596.

🏃 View run nebulous-fox-882 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/4d17b408a37c428f8ef4ebd0e41a7ca4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:27:55,153] Trial 5 finished with value: 23.465148975467272 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.0018085113575329569}. Best is trial 2 with value: 3.899796879593596.

🏃 View run bright-skunk-400 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/3a8c95a4aacd4432917c6da51fb66d73
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:28:20,109] Trial 6 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:28:35,581] Trial 7 finished with value: 4.682463307229885 and parameters: {'model': 'RF', 'n_estimators': 286, 'max_depth': 7}. Best is trial 2 with value: 3.899796879593596.

🏃 View run vaunted-shrew-760 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d51a163a7d2a47dd8f62dad430200455
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run handsome-kite-489 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/697611c554a14d7bb0f3e500ba765e6f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:28:57,895] Trial 8 finished with value: 12.677025262149844 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.18328537133346606}. Best is trial 2 with value: 3.899796879593596.

🏃 View run persistent-chimp-762 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/bed6b98ca4604c1d8c16a699bc2cf1e4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:29:11,224] Trial 10 finished with value: 5.059342206760051 and parameters: {'model': 'DT', 'criterion': 'friedman_mse', 'max_depth': 10}. Best is trial 2 with value: 3.899796879593596.

🏃 View run burly-penguin-212 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/9f24bb3c4de142eb984652e16fc37e73
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:29:27,639] Trial 11 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run painted-mouse-516 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/9b6e31ec21b44762a8f0f361077041f6
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:29:47,610] Trial 9 finished with value: 4.224805194559345 and parameters: {'model': 'RF', 'n_estimators': 223, 'max_depth': 18}. Best is trial 2 with value: 3.899796879593596.

🏃 View run judicious-fawn-222 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/ac109863ab3f4ddd9aff51a2304898a3
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:30:03,800] Trial 13 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run spiffy-ox-707 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/73baa6449a1540bc99659f8b4acc4e55
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:30:07,226] Trial 12 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run nebulous-pug-189 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d26604deda084c3a96c5892ad34e4338
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:30:35,235] Trial 14 finished with value: 4.442875373879192 and parameters: {'model': 'GB', 'n_estimators': 496, 'learning_rate': 0.5416520862881693, 'max_depth': 4}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:30:42,982] Trial 15 finished with value: 3.931550979614258 and parameters: {'model': 'XGB', 'n_estimators': 484, 'learning_rate': 0.5553544116301606, 'max_depth': 5}. Best is trial 2 with value: 3.899796879593596.

🏃 View run bittersweet-cat-847 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/64b1650e96fa4669a73e1628649f1134
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:30:56,432] Trial 17 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run handsome-roo-627 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/a8061a69f91e408b9d7cfb0063a64e33
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run languid-finch-636 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/7acc120560f54a74a466f19f29e26ab8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:31:15,893] Trial 16 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run lyrical-hen-847 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/3f88f49f92c24275bba25f3ec9df0071
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:31:32,895] Trial 18 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:31:44,527] Trial 20 finished with value: 24.979236602783203 and parameters: {'model': 'XGB', 'n_estimators': 76, 'learning_rate': 0.011916185948179947, 'max_depth': 12}. Best is trial 2 with value: 3.899796879593596.

🏃 View run charming-chimp-635 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/dcf0e5adf0554a01aff1ed5c56b6e51f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run adventurous-gnu-991 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/4d4e91930e1e48248da04222c82ae811
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:31:55,261] Trial 19 finished with value: 7.452429294586182 and parameters: {'model': 'XGB', 'n_estimators': 54, 'learning_rate': 0.042608446058162885, 'max_depth': 13}. Best is trial 2 with value: 3.899796879593596.

🏃 View run burly-stork-765 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/54f1b24ef5954e3eb953cf1809a9f882
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:32:15,759] Trial 21 finished with value: 4.669899953069033 and parameters: {'model': 'GB', 'n_estimators': 63, 'learning_rate': 0.8872084901537012, 'max_depth': 19}. Best is trial 2 with value: 3.899796879593596.

🏃 View run clumsy-turtle-739 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/978ce1679f9743508cc2e011dc17c7e2
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:32:35,258] Trial 22 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run zealous-kit-490 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/2e5c4fc2f089424e85ffea53d432b4b3
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run nimble-sheep-404 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d87fab4aef0e4f81b325b9d7d532406a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:32:52,547] Trial 24 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:32:55,307] Trial 23 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:33:16,331] Trial 26 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run dapper-flea-660 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/981518f9d2634d7ba510c7cb78bc1de7
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run fortunate-mouse-385 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/ebaf6ee90c4f426993580154a3606f61
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:33:31,299] Trial 25 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run crawling-sow-206 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/9820934aa5cd484e8e29caf85126a3ca
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:33:44,152] Trial 27 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:33:59,692] Trial 28 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run rare-sow-347 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/703c7117510441fda0d407503f1e6053
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run kindly-sheep-876 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/70c9a2ed64e5406d85944478a773c0b8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:34:27,743] Trial 29 finished with value: 4.246907638410425 and parameters: {'model': 'RF', 'n_estimators': 351, 'max_depth': 9}. Best is trial 2 with value: 3.899796879593596.

🏃 View run unequaled-toad-606 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d9ec4f225ed5437392d0c9c9c26bad65
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:34:35,304] Trial 31 finished with value: 5.089460183230972 and parameters: {'model': 'DT', 'criterion': 'poisson', 'max_depth': 16}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:34:48,060] Trial 30 finished with value: 5.143833556728576 and parameters: {'model': 'GB', 'n_estimators': 372, 'learning_rate': 0.966540153462663, 'max_depth': 9}. Best is trial 2 with value: 3.899796879593596.

🏃 View run able-goose-511 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/7a082ffc6a05474aa3685a9f37c6197d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run traveling-grouse-176 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/b582bf6003b946168d4ab188d6945f18
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:35:07,327] Trial 32 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run carefree-ray-560 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/ab4a864387c24222bea96ddd443de84d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:35:27,358] Trial 33 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run painted-goat-716 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/a8e6f4666a4b4b1b973f051ea294690c
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:35:40,870] Trial 34 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run vaunted-doe-184 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/d7d5e735cbb3486b92b712d6f77af301
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:35:57,961] Trial 35 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:35:59,941] Trial 36 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run flawless-dove-782 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/928b0611ba024aa080d35c87157fbd19
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run bemused-hound-188 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/898aae4f92bb4da8ac98aa51db4abfa8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:36:19,809] Trial 37 finished with value: 38.23241068181609 and parameters: {'model': 'SVR', 'kernel_svm': 'rbf', 'c_rbf': 0.3095935619633146, 'gamma_rbf': 0.20265973604819162}. Best is trial 2 with value: 3.899796879593596.

🏃 View run mercurial-flea-899 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/8c3b578c78714dd59daa5696da5d884b
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:36:31,997] Trial 38 finished with value: 18.86977091967763 and parameters: {'model': 'SVR', 'kernel_svm': 'rbf', 'c_rbf': 4.7879292358385115, 'gamma_rbf': 0.0038466888880396657}. Best is trial 2 with value: 3.899796879593596.

🏃 View run indecisive-ram-871 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/e20a3d6c0dc4448b90adcd626c7cb249
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:36:43,370] Trial 39 finished with value: 5.237449324962295 and parameters: {'model': 'DT', 'criterion': 'squared_error', 'max_depth': 20}. Best is trial 2 with value: 3.899796879593596.

🏃 View run gifted-carp-559 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/e32d8d346f534546ab73c75b7c6cc398
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:36:51,375] Trial 40 finished with value: 4.6527505320835285 and parameters: {'model': 'DT', 'criterion': 'squared_error', 'max_depth': 16}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:37:11,840] Trial 42 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run rebellious-fowl-558 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/3c6974d589d74bf29722139dad3a1c88
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run illustrious-croc-250 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/6a5ef248052842dca808f3aa803cc1ee
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:37:31,410] Trial 41 finished with value: 4.258791802896586 and parameters: {'model': 'RF', 'n_estimators': 176, 'max_depth': 16}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:37:36,074] Trial 43 finished with value: 5.48714880605631 and parameters: {'model': 'RF', 'n_estimators': 198, 'max_depth': 6}. Best is trial 2 with value: 3.899796879593596.

🏃 View run welcoming-robin-599 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/bfd6a3d19a164e65bfcfdb8cb569199e
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run bittersweet-rat-40 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/0edfcdc0f62540b28d252ac86fd0b231
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:38:07,794] Trial 45 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run merciful-smelt-983 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/3115306728354b7b9ea06156a4768879
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:38:11,403] Trial 44 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.
[I 2026-06-15 04:38:32,195] Trial 46 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run wistful-asp-923 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/6d68ccce04cf4bdd830bd9293da4b6b5
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:38:35,802] Trial 47 finished with value: 3.899796879593596 and parameters: {'model': 'LR'}. Best is trial 2 with value: 3.899796879593596.

🏃 View run youthful-cod-463 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/efe9828cf776422da124fd3c7eab97a9
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:38:48,052] Trial 48 finished with value: 4.466131210327148 and parameters: {'model': 'XGB', 'n_estimators': 419, 'learning_rate': 0.34552915498323034, 'max_depth': 12}. Best is trial 2 with value: 3.899796879593596.

🏃 View run inquisitive-ram-902 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/b796be627cb24813b666845d61a8c48f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0
🏃 View run wistful-snake-332 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/adce634faa8b46298280d367e1568c37
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0

[I 2026-06-15 04:38:59,475] Trial 49 finished with value: 4.519293308258057 and parameters: {'model': 'XGB', 'n_estimators': 410, 'learning_rate': 0.3640712510837467, 'max_depth': 12}. Best is trial 2 with value: 3.899796879593596.

🏃 View run Best Model at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0/runs/28c36e2e877d4cabb3a0b8d6b4049fa4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/0