In [1]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('CO2_Emissions_Canada.csv')
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
5702,DODGE,Challenger (MDS),MID-SIZE,6.4,8,A8,Z,15.8,9.6,13.0,22,304
1116,AUDI,Q3 QUATTRO,COMPACT,2.0,4,AS6,Z,11.9,8.4,10.3,27,237
855,NISSAN,PATHFINDER,SUV - SMALL,3.5,6,AV,X,12.0,8.9,10.6,27,244
601,JEEP,WRANGLER UNLIMITED 4X4 (4-DOOR),SUV - SMALL,3.6,6,M6,X,15.0,11.4,13.4,21,308
1641,JAGUAR,F-TYPE COUPE,TWO-SEATER,3.0,6,AS8,Z,11.8,8.4,10.3,27,237

In [3]:
cat_cols = ['Make',	'Model', 'Vehicle Class']

for col in cat_cols:
    df[col] = df[col].str.lower()

df = df.drop_duplicates()

x = df.drop(columns=['CO2 Emissions(g/km)'])
y = df['CO2 Emissions(g/km)']
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.2, random_state=42)

In [4]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [5]:
!pip install mlflow dagshub

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.13.0)
Requirement already satisfied: dagshub in /usr/local/lib/python3.12/dist-packages (0.7.0)
Requirement already satisfied: mlflow-skinny==3.13.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.0)
Requirement already satisfied: mlflow-tracing==3.13.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.0)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<49,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (48.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<27 in /usr/local/lib/python3.12/dist-packages (from mlflow) (26.0.0)
Requirement already satisfied: huey<4,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.0.3)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.50)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.117.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.49.0)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.12/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.43.29)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.1)
Requirement already satisfied: botocore<1.44.0,>=1.43.29 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.43.29)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.19.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.18.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.7)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.3)

In [6]:
import dagshub
dagshub.init(
    repo_owner='anni0955', 
    repo_name='CO2-Emission', 
    mlflow=True
)

Accessing as anni0955

Initialized MLflow to track repo "anni0955/CO2-Emission"

Repository anni0955/CO2-Emission initialized!

In [24]:
import mlflow 
mlflow.set_experiment('EXP 3 (Part 2)- OE Fuel Type + Log transformation')

2026/06/15 12:09:43 INFO mlflow.tracking.fluent: Experiment with name 'EXP 3 (Part 2)- OE Fuel Type + Log transformation' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/9bb1d19ed1704d489b9821f65f93a194', creation_time=1781525386576, effective_trace_archival_retention=None, experiment_id='3', last_update_time=1781525386576, lifecycle_stage='active', name='EXP 3 (Part 2)- OE Fuel Type + Log transformation', tags={}, trace_location=None, workspace='default'>

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

import optuna

In [26]:
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
5744,ford,escape awd,suv - small,1.5,4,AS6,X,11.2,8.4,9.9,29,232
6155,mercedes-benz,amg c 63,compact,4.0,8,A9,Z,13.2,8.7,11.2,25,263
2850,kia,optima hybrid ex,mid-size,2.4,4,AM6,X,6.7,6.1,6.4,44,150
2328,bmw,m4 coupe,compact,3.0,6,AM7,Z,14.1,9.7,12.1,23,284
238,chevrolet,silverado,pickup truck - standard,4.3,6,A6,E,18.9,14.2,16.8,17,269

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler, PowerTransformer

In [30]:
transformer = ColumnTransformer([
    ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'), ['Make', 'Model', 'Vehicle Class', 'Transmission']),
    ('oe', OrdinalEncoder(categories=[['N', 'X', 'D', 'Z', 'E']]), ['Fuel Type']),
    ('pt', PowerTransformer(), ['Fuel Consumption City (L/100 km)',	'Fuel Consumption Hwy (L/100 km)',	'Fuel Consumption Comb (L/100 km)',	'Fuel Consumption Comb (mpg)']),
    ('scale', StandardScaler(),['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)'])
])

In [31]:
x_train_trans = transformer.fit_transform(x_train)
x_test_trans = transformer.transform(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [32]:
x_train_trans.shape

(4792, 1582)

In [33]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [ ]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical('model', ['LR', 'SVR','DT', 'RF', 'GB', 'XGB'])

        if model_name == 'LR':
            model = LinearRegression()

        
        elif model_name == 'SVR':
            kernel_svm = trial.suggest_categorical('kernel_svm', ['linear', 'poly', 'rbf'])

            if kernel_svm == 'linear':
                c_linear = trial.suggest_float('c_linear', 1e-3, 10, log=True)
                model = SVR(C=c_linear, kernel='linear')

            elif kernel_svm == 'poly':
                c_poly = trial.suggest_float('c_poly', 1e-3, 10, log=True)
                degree_poly = trial.suggest_int('degree_poly', 1, 4)
                model = SVR(C=c_poly, degree=degree_poly, kernel='poly')

            else:
                c_rbf = trial.suggest_float('c_rbf', 1e-3, 10, log=True)
                gamma_rbf = trial.suggest_float('gamma_rbf', 1e-3, 10, log=True)
                model = SVR(C=c_rbf, gamma=gamma_rbf, kernel='rbf')

        elif model_name == 'DT':
            criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'absolute_error', 'poisson', 'squared_error'])
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = DecisionTreeRegressor(criterion=criterion, max_depth=max_depth)

        elif model_name == 'RF':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42, n_jobs=-1)
        
        elif model_name == 'GB':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = GradientBoostingRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42)

        else:
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = XGBRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42, n_jobs=-1)    

        
        model.fit(x_train_trans, y_train)
        mlflow.log_params(trial.params)

        test_y_pred = model.predict(x_test_trans)
        train_y_pred = model.predict(x_train_trans)

        test_MAE = mean_absolute_error(y_test, test_y_pred)
        train_MAE = mean_absolute_error(y_train, train_y_pred)

        test_RMSE = root_mean_squared_error(y_test, test_y_pred)
        train_RMSE = root_mean_squared_error(y_train, train_y_pred)

        mlflow.log_metric('train_MAE', train_MAE)
        mlflow.log_metric('test_MAE', test_MAE)

        mlflow.log_metric('train_RMSE', train_RMSE)
        mlflow.log_metric('test_RMSE', test_RMSE)

        return test_RMSE

In [ ]:
study = optuna.create_study(direction='minimize', study_name='Model Selection')

with mlflow.start_run(run_name='Best Model') as parent:
    study.optimize(objective, n_trials=50, n_jobs=-1)
    mlflow.log_params(study.best_params)

    mlflow.log_metric('best_score', study.best_value)

[I 2026-06-15 12:13:22,260] A new study created in memory with name: Model Selection
[I 2026-06-15 12:13:39,271] Trial 1 finished with value: 20.319589226791987 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.0070256312163760985}. Best is trial 1 with value: 20.319589226791987.

🏃 View run handsome-crab-404 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/16d55bf3430e49829cde4f7a9e1f2f0d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:13:41,520] Trial 2 finished with value: 4.892590391730232 and parameters: {'model': 'DT', 'criterion': 'poisson', 'max_depth': 15}. Best is trial 2 with value: 4.892590391730232.

🏃 View run serious-fawn-663 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/9d0b85ba5b00440d90e8a3d59a3d7b59
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:15:03,197] Trial 3 finished with value: 4.268830600486034 and parameters: {'model': 'RF', 'n_estimators': 241, 'max_depth': 14}. Best is trial 3 with value: 4.268830600486034.

🏃 View run lyrical-duck-170 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/9f82b793972044fd8d0e4330ea58229e
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:15:03,495] Trial 0 finished with value: 4.2469810305879205 and parameters: {'model': 'RF', 'n_estimators': 258, 'max_depth': 20}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run sneaky-pig-632 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/6486a5c72bf84f67927ded2ae46f7c9c
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run amazing-cod-705 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/9c3f655b3be24bc887b77c69e268d21f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:15:18,014] Trial 4 finished with value: 20.65794467670574 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.011800527647190882}. Best is trial 0 with value: 4.2469810305879205.
[I 2026-06-15 12:15:38,399] Trial 6 finished with value: 27.503611194168187 and parameters: {'model': 'SVR', 'kernel_svm': 'rbf', 'c_rbf': 1.0139666943006087, 'gamma_rbf': 0.1753372715575303}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run gentle-crow-803 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/87f8b0da96f34af399c9db603c8530bf
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run enchanting-fawn-726 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/834fad676b1141ec998386505a187815
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:15:54,052] Trial 5 finished with value: 4.248710911199274 and parameters: {'model': 'GB', 'n_estimators': 261, 'learning_rate': 0.3223076894858235, 'max_depth': 13}. Best is trial 0 with value: 4.2469810305879205.
[I 2026-06-15 12:15:58,593] Trial 7 finished with value: 4.670044898986816 and parameters: {'model': 'XGB', 'n_estimators': 469, 'learning_rate': 0.2971098052135602, 'max_depth': 15}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run languid-finch-715 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/286f35953d874929b7d5e20e68aeb139
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run angry-crow-173 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/64628a4e78944525b89d265e2e74c30c
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run able-cat-781 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/84b58808e70c406b800cdf7ce06967d9
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:16:22,035] Trial 9 finished with value: 4.874366468210494 and parameters: {'model': 'DT', 'criterion': 'friedman_mse', 'max_depth': 18}. Best is trial 0 with value: 4.2469810305879205.
[I 2026-06-15 12:16:26,071] Trial 8 finished with value: 4.428369045257568 and parameters: {'model': 'XGB', 'n_estimators': 90, 'learning_rate': 0.7451448906670003, 'max_depth': 9}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run nebulous-finch-876 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/2a68472cc9174feba0500ded79afa3a8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:16:38,041] Trial 10 finished with value: 10.19678532478589 and parameters: {'model': 'RF', 'n_estimators': 188, 'max_depth': 4}. Best is trial 0 with value: 4.2469810305879205.
[I 2026-06-15 12:16:57,680] Trial 11 finished with value: 4.715186767893564 and parameters: {'model': 'RF', 'n_estimators': 494, 'max_depth': 7}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run awesome-ant-243 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/bd833e9dc33b43208cad99a4af6fd3b4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run sassy-loon-348 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/6b0c9c551bfe427aba2ff98766c484b5
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:18:45,897] Trial 13 finished with value: 4.415136139490489 and parameters: {'model': 'GB', 'n_estimators': 304, 'learning_rate': 0.06496449187809267, 'max_depth': 20}. Best is trial 0 with value: 4.2469810305879205.
[I 2026-06-15 12:18:51,039] Trial 14 finished with value: 10.442578465360485 and parameters: {'model': 'LR'}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run legendary-mare-821 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/83aa106e3f824939a24725eb6a94983c
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:19:20,990] Trial 15 finished with value: 4.372199478537619 and parameters: {'model': 'GB', 'n_estimators': 328, 'learning_rate': 0.9494678039357891, 'max_depth': 11}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run righteous-bat-453 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/ee276ee272804dcb8aae4abb76765972
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:19:21,205] Trial 12 finished with value: 4.442974892331846 and parameters: {'model': 'GB', 'n_estimators': 329, 'learning_rate': 0.02615053893636654, 'max_depth': 19}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run invincible-fish-875 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/ae625755a87f433ea0c3e2dd9beaeb70
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:19:33,555] Trial 16 finished with value: 10.442578465360485 and parameters: {'model': 'LR'}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run silent-jay-988 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/27e83bce365047ebafc4cb3ae75f7797
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run tasteful-dog-858 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/7508c51e66d14f97a80981890d5d710f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:19:45,214] Trial 17 finished with value: 10.442578465360485 and parameters: {'model': 'LR'}. Best is trial 0 with value: 4.2469810305879205.

🏃 View run receptive-gnu-900 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/a5652b6907af4ed3b0dd36542a591786
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:20:09,787] Trial 18 finished with value: 4.2373420555103865 and parameters: {'model': 'RF', 'n_estimators': 183, 'max_depth': 12}. Best is trial 18 with value: 4.2373420555103865.
[I 2026-06-15 12:20:24,562] Trial 19 finished with value: 4.235339140416132 and parameters: {'model': 'RF', 'n_estimators': 182, 'max_depth': 12}. Best is trial 19 with value: 4.235339140416132.

🏃 View run vaunted-swan-36 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/37ffd75ebc404908aa25d1271ec30e80
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:20:51,688] Trial 21 finished with value: 4.269829330732644 and parameters: {'model': 'RF', 'n_estimators': 116, 'max_depth': 11}. Best is trial 19 with value: 4.235339140416132.

🏃 View run big-snipe-910 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/257b692d3c7843acbf5f8a3ce25c4f1a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:20:53,812] Trial 20 finished with value: 4.269451268410523 and parameters: {'model': 'RF', 'n_estimators': 118, 'max_depth': 17}. Best is trial 19 with value: 4.235339140416132.

🏃 View run gentle-midge-424 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/978aab588e5a41b888fbf4c0ca86d6f0
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:21:39,172] Trial 23 finished with value: 4.279620397668315 and parameters: {'model': 'RF', 'n_estimators': 195, 'max_depth': 11}. Best is trial 19 with value: 4.235339140416132.

🏃 View run spiffy-toad-705 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/d944d8f709394122b0899cad62b516f5
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run resilient-cow-601 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/31e8b884d27a43cfaba9468494f47017
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:21:45,524] Trial 22 finished with value: 4.277012385789332 and parameters: {'model': 'RF', 'n_estimators': 169, 'max_depth': 17}. Best is trial 19 with value: 4.235339140416132.

🏃 View run dapper-midge-836 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/940cfaf84ab6468b886d7f67fe0640c4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:21:53,478] Trial 25 finished with value: 4.7995845912479185 and parameters: {'model': 'RF', 'n_estimators': 53, 'max_depth': 7}. Best is trial 19 with value: 4.235339140416132.
[I 2026-06-15 12:21:54,959] Trial 24 finished with value: 4.415003027097977 and parameters: {'model': 'RF', 'n_estimators': 174, 'max_depth': 8}. Best is trial 19 with value: 4.235339140416132.

🏃 View run lyrical-elk-850 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/4f76bb7068d346d4a795b3098c637722
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run bemused-crane-834 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/db741edcf38c41e1aca76233849167d1
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:22:12,967] Trial 27 finished with value: 10.20210935710746 and parameters: {'model': 'RF', 'n_estimators': 250, 'max_depth': 4}. Best is trial 19 with value: 4.235339140416132.
[I 2026-06-15 12:22:49,940] Trial 26 finished with value: 4.207516565205853 and parameters: {'model': 'RF', 'n_estimators': 248, 'max_depth': 13}. Best is trial 26 with value: 4.207516565205853.

🏃 View run calm-boar-501 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/134773fcfd99474ea602c51cc23df503
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:23:04,634] Trial 29 finished with value: 4.496949672698975 and parameters: {'model': 'XGB', 'n_estimators': 387, 'learning_rate': 0.6222285617648887, 'max_depth': 13}. Best is trial 26 with value: 4.207516565205853.

🏃 View run masked-carp-422 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/edb909d2f3094c98a64f840627982529
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:23:07,431] Trial 28 finished with value: 4.219441526641355 and parameters: {'model': 'RF', 'n_estimators': 225, 'max_depth': 13}. Best is trial 26 with value: 4.207516565205853.

🏃 View run languid-owl-958 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/a19d89f89ac24382b7b689bb48a6884d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run gifted-owl-928 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/a57a392d06804650a2f8e0c35c84ba89
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:23:08,986] Trial 30 finished with value: 5.141027091511975 and parameters: {'model': 'DT', 'criterion': 'squared_error', 'max_depth': 10}. Best is trial 26 with value: 4.207516565205853.
[I 2026-06-15 12:24:02,002] Trial 31 finished with value: 4.240474336881016 and parameters: {'model': 'RF', 'n_estimators': 220, 'max_depth': 12}. Best is trial 26 with value: 4.207516565205853.

🏃 View run rebellious-lark-257 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/80bf038544d442f1b21f5c8c8c9a2361
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:24:06,041] Trial 32 finished with value: 4.227505685277483 and parameters: {'model': 'RF', 'n_estimators': 215, 'max_depth': 13}. Best is trial 26 with value: 4.207516565205853.

🏃 View run nimble-chimp-597 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/092bd2ed3e2542c6bb0b27bb539994cc
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:24:44,176] Trial 33 finished with value: 4.269734178765874 and parameters: {'model': 'RF', 'n_estimators': 141, 'max_depth': 14}. Best is trial 26 with value: 4.207516565205853.

🏃 View run intrigued-hound-444 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/18b5d35c84a24d28b6dcf3a55295db11
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:25:44,024] Trial 34 finished with value: 4.226977960546872 and parameters: {'model': 'RF', 'n_estimators': 297, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.

🏃 View run luminous-hen-878 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/e3a7bd89d23f414caf61da94d261d19b
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:00,310] Trial 36 finished with value: 30.35414129466245 and parameters: {'model': 'SVR', 'kernel_svm': 'poly', 'c_poly': 0.8774729572754022, 'degree_poly': 2}. Best is trial 26 with value: 4.207516565205853.

🏃 View run bedecked-deer-858 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/3642d4a5b23d4c39bbace6bf55952d5d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:02,648] Trial 35 finished with value: 4.234190063873733 and parameters: {'model': 'RF', 'n_estimators': 295, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.

🏃 View run classy-roo-513 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/5f64ffa80eb44c56b78662ff91fabb22
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:43,941] Trial 37 finished with value: 6.650060984124668 and parameters: {'model': 'DT', 'criterion': 'absolute_error', 'max_depth': 16}. Best is trial 26 with value: 4.207516565205853.

🏃 View run sneaky-hound-749 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/01b006b395794df2b2f78e8278e0fafc
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:46,628] Trial 38 finished with value: 6.735500907658184 and parameters: {'model': 'DT', 'criterion': 'absolute_error', 'max_depth': 16}. Best is trial 26 with value: 4.207516565205853.

🏃 View run valuable-horse-103 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/571d12acfa3e4a738f244eb4654e75c8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:55,873] Trial 40 finished with value: 56.09556302214769 and parameters: {'model': 'SVR', 'kernel_svm': 'poly', 'c_poly': 0.0015042583863155838, 'degree_poly': 4}. Best is trial 26 with value: 4.207516565205853.

🏃 View run fun-boar-197 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/879ea8f443be40b7935e90951eba13e1
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:26:57,546] Trial 39 finished with value: 53.476305715883896 and parameters: {'model': 'SVR', 'kernel_svm': 'poly', 'c_poly': 0.0034835970908203956, 'degree_poly': 4}. Best is trial 26 with value: 4.207516565205853.

🏃 View run marvelous-mare-363 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/748b84d834ac43a3ab8f9dc736422f26
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:28:23,462] Trial 41 finished with value: 4.245604849726887 and parameters: {'model': 'RF', 'n_estimators': 291, 'max_depth': 14}. Best is trial 26 with value: 4.207516565205853.

🏃 View run brawny-bat-845 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/b218299d663c429c869df60003dacb75
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:28:24,934] Trial 42 finished with value: 4.248249192226857 and parameters: {'model': 'RF', 'n_estimators': 294, 'max_depth': 14}. Best is trial 26 with value: 4.207516565205853.

🏃 View run stylish-dolphin-968 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/02796f5f037a418b95a349af8f069d0f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:30:21,095] Trial 43 finished with value: 4.208360013574842 and parameters: {'model': 'RF', 'n_estimators': 369, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.

🏃 View run abrasive-goat-36 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/bc60cefdd20444ee966a0032ada3dbcd
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:30:22,406] Trial 44 finished with value: 4.210643965466577 and parameters: {'model': 'RF', 'n_estimators': 365, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.

🏃 View run bittersweet-goat-943 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/c7b386af229b4d3f8f9f33728d6b4749
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run amusing-penguin-651 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/74edd173f5644f11884e7fa118eea5fb
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3
🏃 View run secretive-gull-209 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/46be4d53822f4055a3420c5251fe117f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

[I 2026-06-15 12:30:40,489] Trial 45 finished with value: 4.95468807220459 and parameters: {'model': 'XGB', 'n_estimators': 385, 'learning_rate': 0.9854971120558156, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.
[I 2026-06-15 12:30:46,647] Trial 46 finished with value: 4.571562767028809 and parameters: {'model': 'XGB', 'n_estimators': 388, 'learning_rate': 0.526010071106499, 'max_depth': 15}. Best is trial 26 with value: 4.207516565205853.

🏃 View run Best Model at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3/runs/a7f9bb9a54084654ab94b065d2b87db0
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/3

KeyboardInterrupt: