In [1]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('CO2_Emissions_Canada.csv')
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
2494,CHRYSLER,300,FULL-SIZE,3.6,6,A8,X,12.4,7.7,10.3,27,240
2553,FIAT,500 ABARTH HATCHBACK,MINICOMPACT,1.4,4,A6,X,9.6,7.3,8.6,33,200
5459,ACURA,RDX AWD,SUV - SMALL,2.0,4,AS10,Z,11.0,8.6,9.9,29,232
4581,CHEVROLET,EQUINOX AWD,SUV - SMALL,1.6,4,A6,D,8.5,6.1,7.4,38,198
4555,CHEVROLET,COLORADO,PICKUP TRUCK - SMALL,2.5,4,A6,X,12.1,9.2,10.8,26,253

In [5]:
cat_cols = ['Make',	'Model', 'Vehicle Class']

for col in cat_cols:
    df[col] = df[col].str.lower()

df = df.drop_duplicates()

x = df.drop(columns=['CO2 Emissions(g/km)'])
y = df['CO2 Emissions(g/km)']
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.2, random_state=42)

In [6]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 11.6 MB/s eta 0:00:0000:01
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [7]:
!pip install mlflow dagshub

Collecting mlflow
  Downloading mlflow-3.13.0-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 2.8 MB/s eta 0:00:00
Collecting dagshub
  Downloading dagshub-0.7.0-py3-none-any.whl.metadata (12 kB)
Collecting mlflow-skinny==3.13.0 (from mlflow)
  Downloading mlflow_skinny-3.13.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.4 MB/s eta 0:00:00
Collecting mlflow-tracing==3.13.0 (from mlflow)
  Downloading mlflow_tracing-3.13.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<49,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (48.0.1)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.0.3-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.50)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading databricks_sdk-0.117.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 2.9 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.49.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Collecting boto3 (from dagshub)
  Downloading boto3-1.43.29-py3-none-any.whl.metadata (6.6 kB)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.2.0 (from dagshub)
  Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.1)
Collecting botocore<1.44.0,>=1.43.29 (from boto3->dagshub)
  Downloading botocore-1.43.29-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3->dagshub)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (5.0.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.7)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.3)
Downloading mlflow-3.13.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 72.7 MB/s eta 0:00:00:00:010:01
Downloading mlflow_skinny-3.13.0-py3-none-any.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 70.6 MB/s eta 0:00:00:00:01
Downloading mlflow_tracing-3.13.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 55.6 MB/s eta 0:00:00
Downloading dagshub-0.7.0-py3-none-any.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.1/273.1 kB 15.2 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 5.2 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 8.7 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 7.8 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 14.5 MB/s eta 0:00:00
Downloading huey-3.0.3-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 5.5 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 9.4 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading boto3-1.43.29-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 10.3 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading botocore-1.43.29-py3-none-any.whl (15.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 89.9 MB/s eta 0:00:00:00:010:01
Downloading databricks_sdk-0.117.0-py3-none-any.whl (936 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 936.9/936.9 kB 38.9 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 12.8 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.7 MB/s eta 0:00:00
Downloading s3transfer-0.18.0-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.6/88.6 kB 6.6 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 5.8 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, mypy-extensions, marshmallow, jmespath, gunicorn, graphql-core, dacite, backoff, typing-inspect, graphql-relay, gql, docker, botocore, skops, s3transfer, graphene, Flask-CORS, dataclasses-json, databricks-sdk, dagshub-annotation-converter, boto3, mlflow-tracing, mlflow-skinny, dagshub, mlflow
Successfully installed Flask-CORS-6.0.5 appdirs-1.4.4 backoff-2.2.1 boto3-1.43.29 botocore-1.43.29 dacite-1.6.0 dagshub-0.7.0 dagshub-annotation-converter-0.2.0 databricks-sdk-0.117.0 dataclasses-json-0.6.7 docker-7.1.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.0.0 huey-3.0.3 jmespath-1.1.0 marshmallow-3.26.2 mlflow-3.13.0 mlflow-skinny-3.13.0 mlflow-tracing-3.13.0 mypy-extensions-1.1.0 pathvalidate-3.3.1 s3transfer-0.18.0 semver-3.0.4 skops-0.14.0 treelib-1.8.0 typing-inspect-0.9.0

In [8]:
import dagshub
dagshub.init(
    repo_owner='anni0955', 
    repo_name='CO2-Emission', 
    mlflow=True
)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=4769ded3-6625-42f2-a973-7e07de60bdfc&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=c745b960e7f9446a7e8dec93294004c3fc2aa4a2aa8027e2124fe235dc36a828

Accessing as anni0955

Initialized MLflow to track repo "anni0955/CO2-Emission"

Repository anni0955/CO2-Emission initialized!

In [9]:
import mlflow 
mlflow.set_experiment('EXP 2 - without log transforation')

2026/06/15 11:34:51 INFO mlflow.tracking.fluent: Experiment with name 'EXP 2 - without log transforation' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/d193cbbf258d4ad69adac9874e7e5c46', creation_time=1781523291753, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1781523291753, lifecycle_stage='active', name='EXP 2 - without log transforation', tags={}, trace_location=None, workspace='default'>

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

import optuna

In [11]:
df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
3743,gmc,canyon 4wd,pickup truck - small,2.5,4,A6,X,12.7,9.6,11.3,25,263
6732,chevrolet,suburban 4wd,suv - standard,6.2,8,A10,Z,17.2,11.4,14.6,19,343
2529,dodge,dart,mid-size,2.4,4,M6,X,10.5,6.7,8.8,32,205
1315,chevrolet,equinox ffv,suv - small,2.4,4,A6,X,10.5,7.3,9.1,31,209
1725,kia,rondo,station wagon - mid-size,2.0,4,AS6,X,10.6,7.6,9.3,30,214

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [13]:
transformer = ColumnTransformer([
    ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'), ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']),
    ('scale', StandardScaler(),['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)', 'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)', 'Fuel Consumption Comb (mpg)'])
])

In [14]:
x_train_trans = transformer.fit_transform(x_train)
x_test_trans = transformer.transform(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [15]:
x_train_trans.shape

(4792, 1581)

In [16]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

In [17]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical('model', ['LR', 'SVR','DT', 'RF', 'GB', 'XGB'])

        if model_name == 'LR':
            model = LinearRegression()

        
        elif model_name == 'SVR':
            kernel_svm = trial.suggest_categorical('kernel_svm', ['linear', 'poly', 'rbf'])

            if kernel_svm == 'linear':
                c_linear = trial.suggest_float('c_linear', 1e-3, 10, log=True)
                model = SVR(C=c_linear, kernel='linear')

            elif kernel_svm == 'poly':
                c_poly = trial.suggest_float('c_poly', 1e-3, 10, log=True)
                degree_poly = trial.suggest_int('degree_poly', 1, 4)
                model = SVR(C=c_poly, degree=degree_poly, kernel='poly')

            else:
                c_rbf = trial.suggest_float('c_rbf', 1e-3, 10, log=True)
                gamma_rbf = trial.suggest_float('gamma_rbf', 1e-3, 10, log=True)
                model = SVR(C=c_rbf, gamma=gamma_rbf, kernel='rbf')

        elif model_name == 'DT':
            criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'absolute_error', 'poisson', 'squared_error'])
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = DecisionTreeRegressor(criterion=criterion, max_depth=max_depth)

        elif model_name == 'RF':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42, n_jobs=-1)
        
        elif model_name == 'GB':
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = GradientBoostingRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42)

        else:
            n_estimators = trial.suggest_int('n_estimators', 50, 500)
            learning_rate = trial.suggest_float('learning_rate', 1e-2, 1)
            max_depth = trial.suggest_int('max_depth', 4, 20)
            model = XGBRegressor(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth, random_state=42, n_jobs=-1)    

        
        model.fit(x_train_trans, y_train)
        mlflow.log_params(trial.params)

        test_y_pred = model.predict(x_test_trans)
        train_y_pred = model.predict(x_train_trans)

        test_MAE = mean_absolute_error(y_test, test_y_pred)
        train_MAE = mean_absolute_error(y_train, train_y_pred)

        test_RMSE = root_mean_squared_error(y_test, test_y_pred)
        train_RMSE = root_mean_squared_error(y_train, train_y_pred)

        mlflow.log_metric('train_MAE', train_MAE)
        mlflow.log_metric('test_MAE', test_MAE)

        mlflow.log_metric('train_RMSE', train_RMSE)
        mlflow.log_metric('test_RMSE', test_RMSE)

        return test_RMSE

In [18]:
study = optuna.create_study(direction='minimize', study_name='Model Selection')

with mlflow.start_run(run_name='Best Model') as parent:
    study.optimize(objective, n_trials=50, n_jobs=-1)
    mlflow.log_params(study.best_params)

    mlflow.log_metric('best_score', study.best_value)

[I 2026-06-15 11:35:47,244] A new study created in memory with name: Model Selection
[I 2026-06-15 11:35:59,440] Trial 0 finished with value: 21.909942381005294 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 0.003710111866700193}. Best is trial 0 with value: 21.909942381005294.

🏃 View run zealous-mare-999 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/3dc59e2dbcbe47b98d61bbf21f8c33ab
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:36:01,211] Trial 1 finished with value: 4.821113109588623 and parameters: {'model': 'XGB', 'n_estimators': 345, 'learning_rate': 0.8915000956031599, 'max_depth': 13}. Best is trial 1 with value: 4.821113109588623.

🏃 View run clean-boar-342 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/263853bea3d6409bb4036d41f9c61399
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:36:25,945] Trial 3 finished with value: 4.414655936103098 and parameters: {'model': 'RF', 'n_estimators': 233, 'max_depth': 8}. Best is trial 3 with value: 4.414655936103098.

🏃 View run classy-smelt-478 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/e4227b9e45e741a18ccbcfb10003395a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:37:05,619] Trial 4 finished with value: 6.681934490882889 and parameters: {'model': 'DT', 'criterion': 'absolute_error', 'max_depth': 9}. Best is trial 3 with value: 4.414655936103098.

🏃 View run persistent-skunk-800 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/edc05e3e95a7406283e1c5ca47db6377
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:37:11,464] Trial 5 finished with value: 4.755068410711672 and parameters: {'model': 'GB', 'n_estimators': 125, 'learning_rate': 0.7800681511466117, 'max_depth': 5}. Best is trial 3 with value: 4.414655936103098.

🏃 View run rambunctious-pig-665 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/57d8575461254df39fd2a5bbdfac7c8d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:37:21,295] Trial 2 finished with value: 4.2228961892992265 and parameters: {'model': 'RF', 'n_estimators': 362, 'max_depth': 15}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run inquisitive-stag-377 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/6f6bf74575c74258876323475375f5f8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:37:50,659] Trial 6 finished with value: 4.236527466345476 and parameters: {'model': 'RF', 'n_estimators': 244, 'max_depth': 12}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run worried-shrike-732 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/195a4eb335a54e4f9fcc263e93a9ca30
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:37:53,916] Trial 8 finished with value: 5.2013812670144155 and parameters: {'model': 'LR'}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run adaptable-sow-982 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/dad215b22cd349c599a0278a3a3dd4b9
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:38:12,721] Trial 7 finished with value: 4.3531416279509525 and parameters: {'model': 'GB', 'n_estimators': 374, 'learning_rate': 0.13454821905259728, 'max_depth': 15}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run puzzled-stoat-885 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/ae4ee24648824c2fa948f8faadf8f3f3
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:38:48,337] Trial 10 finished with value: 4.530586348991059 and parameters: {'model': 'GB', 'n_estimators': 318, 'learning_rate': 0.4762106302659387, 'max_depth': 13}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run rumbling-bird-687 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/df5f8d4cf8ac47419f0e9e1d40f1c258
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:39:07,288] Trial 9 finished with value: 4.227193080065797 and parameters: {'model': 'RF', 'n_estimators': 293, 'max_depth': 17}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run calm-skunk-955 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/852ea04171af4467a8e81ab5d4ef7fc4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:41:09,167] Trial 11 finished with value: 4.2359147991142265 and parameters: {'model': 'RF', 'n_estimators': 435, 'max_depth': 19}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run rebellious-deer-263 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/7e37db773b8e41caa5560b8ab944fdb4
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:41:45,386] Trial 12 finished with value: 4.239434761305115 and parameters: {'model': 'RF', 'n_estimators': 484, 'max_depth': 20}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run unruly-crab-475 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/feff92c416644711a92641ba8128cf0a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:01,242] Trial 14 finished with value: 4.234417090690258 and parameters: {'model': 'RF', 'n_estimators': 245, 'max_depth': 17}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run serious-shad-33 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/36c726a7de03477fac603cf467795477
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:26,316] Trial 15 finished with value: 8.783546447753906 and parameters: {'model': 'XGB', 'n_estimators': 75, 'learning_rate': 0.027694824138536134, 'max_depth': 17}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run trusting-perch-770 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/680609a80a454ce98308c186a5073504
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:29,693] Trial 16 finished with value: 5.2013812670144155 and parameters: {'model': 'LR'}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run rumbling-bass-343 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/176f040bc751471697b7157625781b57
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:34,881] Trial 13 finished with value: 4.243378408873384 and parameters: {'model': 'RF', 'n_estimators': 480, 'max_depth': 19}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run unleashed-frog-87 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/55ec87d21e8043dd96d8f7bf1e149777
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:42,136] Trial 17 finished with value: 60.56907041001933 and parameters: {'model': 'SVR', 'kernel_svm': 'rbf', 'c_rbf': 0.2214691908676347, 'gamma_rbf': 5.577150176881295}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run puzzled-ant-78 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/a9e62e47eea444a9927c6621b8c91f4d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:43:58,228] Trial 18 finished with value: 54.54906148409454 and parameters: {'model': 'SVR', 'kernel_svm': 'poly', 'c_poly': 0.00245432412088014, 'degree_poly': 3}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run indecisive-vole-867 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/0278df7ae3194d3b98dcf23c24c0bca9
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run incongruous-wasp-637 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/a7c3edd84a0a4e63bd8ea8741582de28
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:44:17,610] Trial 19 finished with value: 4.840096330548382 and parameters: {'model': 'DT', 'criterion': 'friedman_mse', 'max_depth': 16}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run melodic-shrew-215 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/4c84f5b805b34927a91cb938bd7ee1f2
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:44:22,863] Trial 20 finished with value: 4.457196976549548 and parameters: {'model': 'DT', 'criterion': 'squared_error', 'max_depth': 16}. Best is trial 2 with value: 4.2228961892992265.
[I 2026-06-15 11:45:56,916] Trial 21 finished with value: 4.261659973222167 and parameters: {'model': 'RF', 'n_estimators': 245, 'max_depth': 18}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run bouncy-ant-388 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/0678783c468b412889806b99c2c01316
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:45:58,213] Trial 22 finished with value: 4.25514899231113 and parameters: {'model': 'RF', 'n_estimators': 253, 'max_depth': 18}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run indecisive-kite-783 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/9ee91316d5cc4e3fa9f8917239a21c90
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:47:18,567] Trial 24 finished with value: 4.257918520021588 and parameters: {'model': 'RF', 'n_estimators': 305, 'max_depth': 14}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run nosy-pig-790 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/68e892b092304df6a7eae8a9b5a377d2
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:47:20,415] Trial 23 finished with value: 4.254619881482575 and parameters: {'model': 'RF', 'n_estimators': 310, 'max_depth': 14}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run painted-mouse-479 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/847287e0ed474c51aa39c707ac0c94f8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:47:49,827] Trial 25 finished with value: 4.25863009823587 and parameters: {'model': 'RF', 'n_estimators': 161, 'max_depth': 11}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run capable-kite-523 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/cc000a9cfcd64bd196d364fc71c85731
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:47:50,963] Trial 26 finished with value: 4.25468451027449 and parameters: {'model': 'RF', 'n_estimators': 175, 'max_depth': 11}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run bold-hound-212 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/d715a4a90dec44758aef25a1177b149a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run suave-penguin-546 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/f401c843815f4ee6b0be3cd0ed4e2b99
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run handsome-swan-340 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/0fd1b4c37fd64c019c59320bc6bfc36b
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:47:56,426] Trial 27 finished with value: 5.2013812670144155 and parameters: {'model': 'LR'}. Best is trial 2 with value: 4.2228961892992265.
[I 2026-06-15 11:47:57,132] Trial 28 finished with value: 5.2013812670144155 and parameters: {'model': 'LR'}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run peaceful-crab-754 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/f90202030e324347bdebdd847ce9e60e
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:48:25,139] Trial 29 finished with value: 4.574560642242432 and parameters: {'model': 'XGB', 'n_estimators': 395, 'learning_rate': 0.4548352959473594, 'max_depth': 16}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run agreeable-turtle-31 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/2a059b043247403ea945021c95586efa
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:48:41,150] Trial 30 finished with value: 5.718483855803601 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 9.905624873733801}. Best is trial 2 with value: 4.2228961892992265.
[I 2026-06-15 11:48:49,674] Trial 31 finished with value: 5.693721911670799 and parameters: {'model': 'SVR', 'kernel_svm': 'linear', 'c_linear': 8.511070249788117}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run burly-grub-732 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/0db8168b10444261bebd688c39394a5d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:51:31,299] Trial 32 finished with value: 4.241652774363195 and parameters: {'model': 'RF', 'n_estimators': 433, 'max_depth': 20}. Best is trial 2 with value: 4.2228961892992265.

🏃 View run melodic-mare-452 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/b5bded9d0ce24dc6b1e2d5b799459f80
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run upbeat-boar-106 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/82f57f10e7fb46d5a2e47b54f8e1d184
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:51:39,964] Trial 33 finished with value: 4.232587575328972 and parameters: {'model': 'RF', 'n_estimators': 425, 'max_depth': 19}. Best is trial 2 with value: 4.2228961892992265.
[I 2026-06-15 11:54:39,765] Trial 35 finished with value: 4.218483425441883 and parameters: {'model': 'RF', 'n_estimators': 389, 'max_depth': 17}. Best is trial 35 with value: 4.218483425441883.

🏃 View run mercurial-cow-174 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/c874f3914661431dbf831f6877b179b5
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:54:43,561] Trial 34 finished with value: 4.2237603300701405 and parameters: {'model': 'RF', 'n_estimators': 421, 'max_depth': 18}. Best is trial 35 with value: 4.218483425441883.

🏃 View run sassy-kit-923 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/1d78bca2a01f4266b79080dc58805582
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:57:31,788] Trial 37 finished with value: 4.2089722988686775 and parameters: {'model': 'RF', 'n_estimators': 375, 'max_depth': 17}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run masked-doe-79 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/29774d1672314b0bacfd0143f62ba452
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run abrasive-stork-586 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/a04265657947407b8fcd77dc361b8103
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:57:59,071] Trial 36 finished with value: 4.2242431217298515 and parameters: {'model': 'RF', 'n_estimators': 404, 'max_depth': 18}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run grandiose-chimp-848 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/83d6d33e4e8245d59cfda26b1f69db4a
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:58:21,573] Trial 38 finished with value: 4.427204608917236 and parameters: {'model': 'XGB', 'n_estimators': 387, 'learning_rate': 0.5765535669065008, 'max_depth': 15}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run chill-bird-106 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/056579f07b824bed8edeb163352ee658
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 11:59:05,579] Trial 39 finished with value: 4.682937145233154 and parameters: {'model': 'XGB', 'n_estimators': 357, 'learning_rate': 0.5455145508797024, 'max_depth': 15}. Best is trial 37 with value: 4.2089722988686775.
[I 2026-06-15 11:59:18,083] Trial 40 finished with value: 4.60034715254273 and parameters: {'model': 'GB', 'n_estimators': 349, 'learning_rate': 0.2272422856411389, 'max_depth': 15}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run tasteful-goose-525 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/ce7de1fb083844ad914ea7ca6d86317f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:00:09,889] Trial 41 finished with value: 4.511894884027161 and parameters: {'model': 'GB', 'n_estimators': 459, 'learning_rate': 0.2299418441559452, 'max_depth': 14}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run caring-steed-790 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/4d54f89b90cf4f5282368e783924bad2
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run capricious-skunk-51 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/d85b5643ef4442019243b6ff0d6c280d
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:01:27,402] Trial 42 finished with value: 4.223300657895682 and parameters: {'model': 'RF', 'n_estimators': 410, 'max_depth': 18}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run righteous-gull-39 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/37d63ceaabba4cc48ac905d935622e61
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:02:15,407] Trial 43 finished with value: 4.22376009181152 and parameters: {'model': 'RF', 'n_estimators': 408, 'max_depth': 18}. Best is trial 37 with value: 4.2089722988686775.

🏃 View run calm-rook-552 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/8da91e57f5194ca49494fa56e230a006
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:03:43,443] Trial 44 finished with value: 4.22188306561257 and parameters: {'model': 'RF', 'n_estimators': 407, 'max_depth': 17}. Best is trial 37 with value: 4.2089722988686775.
[I 2026-06-15 12:04:14,419] Trial 45 finished with value: 4.2043193857439425 and parameters: {'model': 'RF', 'n_estimators': 368, 'max_depth': 17}. Best is trial 45 with value: 4.2043193857439425.

🏃 View run gaudy-panda-266 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/fce9736829c64a669fe74ca5d3ded6c0
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run melodic-loon-368 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/8e6416bcc2c04ce688bdb60cb7fcc2f7
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:04:51,453] Trial 47 finished with value: 12.71604741369479 and parameters: {'model': 'DT', 'criterion': 'poisson', 'max_depth': 4}. Best is trial 45 with value: 4.2043193857439425.

🏃 View run mysterious-slug-317 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/82d32d9a3f2848d9a9af62cc27d1eab8
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:05:23,594] Trial 46 finished with value: 4.205364978844793 and parameters: {'model': 'RF', 'n_estimators': 361, 'max_depth': 17}. Best is trial 45 with value: 4.2043193857439425.
[I 2026-06-15 12:07:32,654] Trial 48 finished with value: 4.2697988538845 and parameters: {'model': 'RF', 'n_estimators': 343, 'max_depth': 16}. Best is trial 45 with value: 4.2043193857439425.

🏃 View run dapper-fox-943 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/71998c4cc90c40bf86ac23ec41a05732
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1

[I 2026-06-15 12:07:51,903] Trial 49 finished with value: 4.268716894052171 and parameters: {'model': 'RF', 'n_estimators': 335, 'max_depth': 16}. Best is trial 45 with value: 4.2043193857439425.

🏃 View run funny-conch-734 at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/cabb6e5f699c4d378caade0f7064fbd1
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1
🏃 View run Best Model at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1/runs/3a9b3885f7eb40c98833159b492c8b7f
🧪 View experiment at: https://dagshub.com/anni0955/CO2-Emission.mlflow/#/experiments/1